In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("House Price Prediction Dataset.csv")
df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

In [9]:
df.columns

Index(['Id', 'Area', 'Bedrooms', 'Bathrooms', 'Floors', 'YearBuilt',
       'Location', 'Condition', 'Garage', 'Price'],
      dtype='object')

In [5]:
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

In [6]:
df.tail()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   object
 7   Condition  2000 non-null   object
 8   Garage     2000 non-null   object
 9   Price      2000 non-null   int64
dtypes: int64(7), object(3)
memory usage: 156.4+ KB

In [8]:
df.describe()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price
count,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000
mean,1000.500000,2786.209500,3.003500,2.55250,1.993500,1961.446000,537676.855000
std,577.494589,1295.146799,1.424606,1.10899,0.809188,35.926695,276428.845719
min,1.000000,501.000000,1.000000,1.00000,1.000000,1900.000000,50005.000000
25%,500.750000,1653.000000,2.000000,2.00000,1.000000,1930.000000,300098.000000
50%,1000.500000,2833.000000,3.000000,3.00000,2.000000,1961.000000,539254.000000
75%,1500.250000,3887.500000,4.000000,4.00000,3.000000,1993.000000,780086.000000
max,2000.000000,4999.000000,5.000000,4.00000,3.000000,2023.000000,999656.000000

In [15]:
df.isna().sum()

Id           0
Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
Location     0
Condition    0
Garage       0
Price        0
dtype: int64

In [11]:
df.isnull().sum()

Id           0
Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
Location     0
Condition    0
Garage       0
Price        0
dtype: int64

In [13]:
numerical_columns = df.select_dtypes(include=np.number).columns
numerical_columns

Index(['Id', 'Area', 'Bedrooms', 'Bathrooms', 'Floors', 'YearBuilt', 'Price'], dtype='object')

In [14]:
categorical_columns = df.select_dtypes(include='object').columns
categorical_columns

Index(['Location', 'Condition', 'Garage'], dtype='object')

In [37]:
df_encoded = pd.get_dummies(df,columns=['Location', 'Condition', 'Garage'])

In [38]:
df_encoded = df_encoded.astype(int)

In [41]:
df_encoded.shape

(2000, 17)

In [39]:
df_encoded.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price,Location_Downtown,Location_Rural,Location_Suburban,Location_Urban,Condition_Excellent,Condition_Fair,Condition_Good,Condition_Poor,Garage_No,Garage_Yes
0,1,1360,5,4,3,1970,149919,1,0,0,0,1,0,0,0,1,0
1,2,4272,5,4,3,1958,424998,1,0,0,0,1,0,0,0,1,0
2,3,3592,2,2,3,1938,266746,1,0,0,0,0,0,1,0,1,0
3,4,966,4,2,2,1902,244020,0,0,1,0,0,1,0,0,0,1
4,5,4926,1,4,2,1975,636056,1,0,0,0,0,1,0,0,0,1

In [18]:
y = df['Price']

In [21]:
X = df.drop('Price', axis=1)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [24]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((1600, 9), (400, 9), (1600,), (400,))

In [19]:
df.loc[:, ['Area', 'Bedrooms', 'Bathrooms']]

      Area  Bedrooms  Bathrooms
0     1360         5          4
1     4272         5          4
2     3592         2          2
3      966         4          2
4     4926         1          4
...    ...       ...        ...
1995  4994         5          4
1996  3046         5          2
1997  1062         5          1
1998  4062         3          1
1999  2989         5          1

[2000 rows x 3 columns]

In [20]:
df[numerical_columns].skew()

Id           0.000000
Area        -0.038552
Bedrooms    -0.021753
Bathrooms   -0.066546
Floors       0.011837
YearBuilt   -0.001577
Price       -0.064351
dtype: float64

In [34]:
df_encoded.shape

(2000, 17)

In [35]:

df_encoded.isna().sum()

Id                     0
Area                   0
Bedrooms               0
Bathrooms              0
Floors                 0
YearBuilt              0
Price                  0
Location_Downtown      0
Location_Rural         0
Location_Suburban      0
Location_Urban         0
Condition_Excellent    0
Condition_Fair         0
Condition_Good         0
Condition_Poor         0
Garage_No              0
Garage_Yes             0
dtype: int64

In [36]:
df_encoded.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price,Location_Downtown,Location_Rural,Location_Suburban,Location_Urban,Condition_Excellent,Condition_Fair,Condition_Good,Condition_Poor,Garage_No,Garage_Yes
0,1,1360,5,4,3,1970,149919,1,0,0,0,1,0,0,0,1,0
1,2,4272,5,4,3,1958,424998,1,0,0,0,1,0,0,0,1,0
2,3,3592,2,2,3,1938,266746,1,0,0,0,0,0,1,0,1,0
3,4,966,4,2,2,1902,244020,0,0,1,0,0,1,0,0,0,1
4,5,4926,1,4,2,1975,636056,1,0,0,0,0,1,0,0,0,1